# Generated by Django 5.0.6 on 2024-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept', models.CharField(choices=[('CSE', 'Computer science and Engineering'), ('EEE', 'Electrical and Engineering'), ('ECE', 'Electronics and communication Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('Physics', 'Physics'), ('Tamil', 'Tamil'), ('English', 'English'), ('Maths', 'Maths'), ('History', 'History')], max_length=255)),
            ],
        ),
    ]
