# Generated by Django 5.0.6 on 2024-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Website', '0004_alter_dep_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='Dept',
            field=models.CharField(choices=[('CSE', 'Computer science and Engineering'), ('EEE', 'Electrical and Engineering'), ('ECE', 'Electronics and communication Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=255),
        ),
    ]
