# Generated by Django 5.0.6 on 2024-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Website', '0010_st_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Col_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=255)),
                ('Fees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hos_Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=255)),
                ('Fees', models.FloatField()),
            ],
        ),
    ]
