# Generated by Django 5.0.6 on 2024-07-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Website', '0011_col_fees_hos_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
