# Generated by Django 5.0.6 on 2024-07-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_Website', '0013_alter_st_reg_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='st_registration',
            old_name='Biology',
            new_name='Fundamentals_of_engg',
        ),
    ]
