# Generated by Django 5.0.6 on 2024-07-04 07:00

import College_Website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_Website', '0014_rename_biology_st_registration_fundamentals_of_engg'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=College_Website.models.getFileName)),
            ],
        ),
    ]
